apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: carrier-api
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
    spec:
      containers:
        - image: ${IMAGE_URL}
          env:
            - name: FMCSA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: fmcsa-api-key
                  key: latest
            - name: INTERNAL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: internal-api-key
                  key: latest
          ports:
            - containerPort: 8080
      serviceAccountName: default
