apiVersion: run.googleapis.com/v1
kind: Service
metadata:
  name: carrier-api
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
    spec:
      containers:
        - image: ${IMAGE_URL}
          env:
            # FMCSA API key from Secret Manager
            - name: FMCSA_API_KEY
              valueSource:
                secretKeyRef:
                  secret: fmcsa-api-key
                  version: latest
            # Internal API key from Secret Manager
            - name: INTERNAL_API_KEY
              valueSource:
                secretKeyRef:
                  secret: internal-api-key
                  version: latest
          ports:
            - containerPort: 8080
      serviceAccountName: default
